# Generated by Django 3.2.4 on 2021-06-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeModel',
            fields=[
                ('No', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('UserName', models.CharField(max_length=30, unique=True)),
                ('Comments', models.CharField(max_length=200)),
                ('Uploads', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30, unique=True)),
                ('Password', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Username', models.CharField(max_length=30, unique=True)),
                ('Email', models.EmailField(max_length=20, unique=True)),
                ('Contact', models.IntegerField()),
                ('Password', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30, unique=True)),
                ('Password', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
